version: '3'

x-base: &base
    env_file:
        - .env

networks:
  etl_network:
    driver: bridge

services:
  postgres:
    image: postgres:latest
    container_name: postgres_etl
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U app -d movies_database" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    networks:
      - etl_network
    ports:
      - ${POSTGRES_PORT}:5432

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - ${ELASTIC_PORT}:9200
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
