version: '3'

x-base: &base
    env_file:
        - .env

networks:
  etl_network:
    driver: bridge

services:
  postgres:
    image: postgres:latest
    container_name: postgres_sqlite_to_postgres
    restart: always
    networks:
      - etl_network
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U app -d movies_database" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    expose:
      - ${POSTGRES_PORT}

  sql_to_postges:
    build:
      context: sqlite_to_postgres
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - etl_network